# Generated by Django 2.2.1 on 2019-05-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_id', models.CharField(max_length=4)),
                ('airport_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=8)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('plane_model', models.CharField(max_length=60)),
                ('arrival_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='core.Airport')),
                ('departure_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='core.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_type', models.IntegerField()),
                ('free_places', models.IntegerField()),
                ('price', models.IntegerField()),
                ('luggage_price', models.IntegerField()),
                ('child_place_price', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Flight')),
            ],
        ),
    ]
